BCM: int
OUT: int
HIGH: int
LOW: int

def setmode(mode: int) -> None: ...
def setup(channel: int, direction: int) -> None: ...
def output(channel: int, value: int) -> None: ...
def cleanup() -> None: ...